---
title: "Algorithms"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Algorithms}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Testing algorithms for SDMs

```{r preparing_data}
library(caretSDM)
sa <- sdm_area('input_data/parana_paraguay.gpkg', 
               cell_size = 25000, 
               crs = 6933, 
               gdal = T) |> 
  add_predictors(stars::read_stars(list.files("input_data/WorldClim_data_current/", 
                                              full.names = T), 
                                   along = "band", 
                                   normalize_path = F)) |> 
  add_scenarios() |> 
  dplyr::select(c("LENGTH_KM", "DIST_DN_KM", "DIST_UP_KM", "CATCH_SKM", 
                  "UPLAND_SKM", "DIS_AV_CMS","ORD_STRA","X1.tif", "X2.tif", "X3.tif",
                  "X4.tif", "X5.tif", "X6.tif", "X7.tif", "X12.tif", 
                  "X13.tif", "X14.tif", "X15.tif")) |> 
  set_predictor_names(c("LENGTH_KM", "DIST_DN_KM", "DIST_UP_KM", "CATCH_SKM",
                        "UPLAND_SKM", "DIS_AV_CMS","ORD_STRA",
                        "bio01","bio02", "bio03", "bio04", "bio05", "bio06", 
                        "bio07", "bio12", "bio13", "bio14", "bio15"))

oc <- occurrences_sdm("input_data/Salminus.csv", crs = 4326) |> 
  join_area(sa)

```

```{r knn}
i <- input_sdm(oc, sa) |> 
  data_clean() |> 
  vif_predictors() |> 
  pseudoabsences(method = "bioclim", variables_selected = "vif") |> 
  train_sdm(algo = c("svmPoly","naive_bayes", "kknn", "nnet", "mda", ), 
            crtl = caret::trainControl(method = "repeatedcv", 
                                       number = 4, 
                                       repeats = 10, 
                                       classProbs = TRUE, 
                                       returnResamp = "all", 
                                       summaryFunction = summary_sdm, 
                                       savePredictions = "all"), 
            variables_selected = "vif")
```

```{r}

```
