test_that("buffer_sdm", {
  skip_on_cran()
  expect_no_error(b <- buffer_sdm(occ, size = 100000, occ_crs = 6933))
  expect_true(sf::st_geometry_type(b) == "POLYGON")
  expect_no_error(b <- buffer_sdm(occ, size = 10000, occ_crs = 6933))
  expect_true(sf::st_geometry_type(b) == "MULTIPOLYGON")
  expect_no_error(b <- buffer_sdm(occ[, -1], size = 10000, occ_crs = 6933))
  expect_true(sf::st_geometry_type(b) == "MULTIPOLYGON")
  expect_error(buffer_sdm(occ[, -3], size = 10000, occ_crs = 6933))
  expect_error(buffer_sdm(occ, size = "10000", occ_crs = 6933))
  expect_error(buffer_sdm(occ, size = 10000, occ_crs = "6933"))
  oc <- occurrences_sdm(occ, occ_crs = 4326)
  expect_no_error(b <- buffer_sdm(oc, size = 100000, occ_crs = 6933))
  expect_true(sf::st_geometry_type(b) == "POLYGON")
  expect_no_error(b <- buffer_sdm(oc, size = 10000, occ_crs = 6933))
  expect_true(sf::st_geometry_type(b) == "MULTIPOLYGON")
  oc <- occurrences_sdm(occ[, -1], occ_crs = 4326)
  expect_no_error(b <- buffer_sdm(oc, size = 10000, occ_crs = 6933))
  expect_true(sf::st_geometry_type(b) == "MULTIPOLYGON")
  expect_error(buffer_sdm(oc, size = "10000", occ_crs = 6933))
  expect_error(buffer_sdm(oc, size = 10000, occ_crs = "6933"))
})

test_that("buffer_sdm - MCP", {
  skip_on_cran()
  expect_no_error(b <- buffer_sdm(occ, size = 100000, occ_crs = 6933, mcp = TRUE))
  expect_true(sf::st_geometry_type(b) == "POLYGON")
  expect_no_error(b <- buffer_sdm(occ[, -1], size = 10000, occ_crs = 6933, mcp = TRUE))
  expect_true(sf::st_geometry_type(b) == "POLYGON")
  expect_error(buffer_sdm(occ, size = 10000, occ_crs = 6933, mcp = "TRUE"))
  oc <- occurrences_sdm(occ, occ_crs = 4326)
  expect_no_error(b <- buffer_sdm(oc, size = 100000, occ_crs = 6933, mcp = TRUE))
  expect_true(sf::st_geometry_type(b) == "POLYGON")
  oc <- occurrences_sdm(occ[, -1], occ_crs = 4326)
  expect_no_error(b <- buffer_sdm(oc, size = 10000, occ_crs = 6933, mcp = TRUE))
  expect_true(sf::st_geometry_type(b) == "POLYGON")
  expect_no_error(b <- buffer_sdm(oc, size = 0, occ_crs = 6933, mcp = TRUE))
  expect_true(sf::st_geometry_type(b) == "POLYGON")
  expect_true(all(sf::st_bbox(b) == sf::st_bbox(oc$occurrences)))
})
