sa <- sdm_area(parana, 0.1)
sa <- add_predictors(sa, bioc)
sa <- select(sa, c("bio1", "bio12"))
sa <- sa |> mutate(div=bio1/bio12, prod=bio1*bio12, sub=bio12-bio1, soma=bio1+bio12)
sa <- add_scenarios(sa)
oc <- occurrences_sdm(occ, crs=6933)
suppressWarnings(oc <- join_area(oc, sa))
i <- input_sdm(oc, sa)

test_that("pseudoabsences - normal", {
  suppressWarnings(i2 <- pseudoabsences(i, method = "bioclim"))
  expect_equal(n_pseudoabsences(i2), n_records(i2))
  expect_equal("bioclim", pseudoabsence_method(i2))
  expect_warning(i2 <- pseudoabsences(i2, method = "random", variables_selected = c("prod", "soma")))
  suppressWarnings(i3 <- vif_predictors(i, th=0.9))
  i3 <- pseudoabsences(i3, method = "bioclim", variables_selected = "vif")
  expect_equal("bioclim", pseudoabsence_method(i3))
  i4 <- pca_predictors(i)
  i4 <- pseudoabsences(i4, method = "bioclim", variables_selected = "pca")
  expect_equal("bioclim", pseudoabsence_method(i4))
})
