---
title: "1. Concatenate functions in caretSDM"
author: '[author name]'
date: "`r Sys.Date()`"
output:
  pdf_document:
    toc: true
    toc_depth: '3'
  html_document:
    toc: true
    toc_float: true
    toc_depth: 3
    theme: flatly
    highlight: tango
    code_folding: show
    df_print: paged
vignette: "%\\VignetteIndexEntry{1. Concatenate functions in caretSDM} %\\VignetteEncoding{UTF-8}
  %\\VignetteEngine{knitr::knitr}\n"
editor_options:
  markdown:
    wrap: 100
---

In caretSDM we always use one central object through out the framework, the
`input_sdm` object. This allows us to concatenate functions, which can be very
useful when running SDMs for the first couple of times. Here we provide a
functioning way to easily run your framework with only three objects.

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
# Open library
library(caretSDM)
set.seed(1)
```

```{r, results="hide"}
# Build sdm_area object
sa <- sdm_area(x = rivs,
  cell_size = 25000,
  output_crs = 6933,
  gdal = TRUE,
  lines_as_sdm_area = TRUE,
  variables_selected = NULL,
  crop_by = NULL
) |>
  add_predictors(pred = bioc,
                 variables_selected = NULL, 
                 gdal = TRUE,
                 lines_as_sdm_area = TRUE) |>
  add_scenarios(scenarios_names = NULL, 
                pred_as_scen = TRUE,
                variables_selected = NULL, 
                stationary = NULL, 
                crop_area = NULL) |>
  select_predictors(c("LENGTH_KM", "DIST_DN_KM", "bio1", "bio4", "bio12"))

# Build occurrences_sdm object
oc <- occurrences_sdm(occ = salm, 
                      occ_crs = 6933,
                      independent_test = NULL,
                      p = 0.1,
                      independent_test_crs = NULL)

# Merge sdm_area and occurrences_sdm and perform pre-processing, processing and projecting.
i <- input_sdm(oc, sa) |>
  data_clean(species = NA, 
           lon = NA, 
           lat = NA,
           capitals = TRUE,
           centroids = TRUE,
           duplicated = TRUE,
           identical = TRUE,
           institutions = TRUE,
           invalid = TRUE,
           terrestrial = TRUE,
           independent_test = TRUE,
           fun = NULL) |>
  multicollinearity_sdm(method = "vifcor",
                        variables_selected = NULL,
                        cumulative_proportion = 0.99,
                        th = 0.5) |>
  pseudoabsences(method = "bioclim", 
                 variables_selected = "vif",
                 n_set = 10,
                 n_pa = NULL,
                 th = 0,
                 size = 1,
                 size_crs = 4326,
                 mcp = FALSE) |>
  train_sdm(
    algo = c("naive_bayes", "kknn"),
    ctrl = caret::trainControl(
      method = "repeatedcv",
      number = 4,
      repeats = 1,
      classProbs = TRUE,
      returnResamp = "all",
      summaryFunction = summary_sdm,
      savePredictions = "all"
    ),
    variables_selected = "vif",
    parallel = FALSE
  ) |>
  predict_sdm(metric = "ROC",
            th = 0.7,
            tp = "prob",
            file = NULL,
            add.current = TRUE) |>
  ensemble_sdm(method = "average",
            metric = NULL,
            fun = NULL) |>
  suppressWarnings()
```

```{r}
i
```

```{r}
plot(i)
```
