# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  "cell_id", # <add_predictors>
  "geometry", # <add_predictors>
  "X", # <occurrences_sdm>
  "Y", # <occurrences_sdm>
  "value", # <pdp_sdm>
  "variable", # <pdp_sdm>
  "yhat", # <pdp_sdm>
  "id", # <pdp_sdm>
  "species", # <plot_occurrences>
  "result", # <plot_occurrences>
  "value", # <plot_occurrences>
  "var1", # <plot_occurrences>
  "var2", # <plot_occurrences>
  "density", # <plot_occurrences>
  "algo", # <predict_sdm>
  ".data", # <predict_sdm>
  "Sensitivity", # <predict_sdm>
  "Specificity", # <predict_sdm>
  "original_id", # <sdm_area>
  "..weighting_factor", # <sdm_area>
  "species", # <select_predictors>
  "species", # <train_sdm>
  "V1", # <tsne_sdm>
  "V2", # <tsne_sdm>
  "cell_id.x", # <write_ensembles>
  "species", # <write_ensembles>
  "sp", # <write_ensembles>
  "sc", # <write_ensembles>
  "geometry", # <write_ensembles>
  NULL
))
